### ISSUE TITLE
‘System.OutOfMemoryException’ was Thrown.

### ISSUE THREAD

**Issue by ArisCuber19** [boss-beep/Proton-Crypter#1]
Hi, I was trying to crypt and exe file and after selecting everything and clicking the build button i received this error.. any fix? Thanks:)
![Screenshot 2021-07-31 151200](https://user-images.githubusercontent.com/58995553/127741081-f6335670-7ce8-4530-a12d-a493ee35ea2b.png)

**Comment by boss-beep** [comment]
I will get to it shortly.Its the first of it reported.Thanks

**Comment by PandoricGalaxy** [comment]
same
